import type { Metadata } from "next";
// import "../styles/globals.css";
import "aos/dist/aos.css";
import "./globals.css";
import Footer from "./components/layout/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>{children}</body>
      <Footer />
    </html>
  );
}
